version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "23:00"
      timezone: "UTC"
